### ISSUE TITLE
RN-2/Feature - реализовать класс Task

### ISSUE THREAD

**Issue by IvanSenchukov** [rexnegotium/rexnegotium#2]
Реализовать класс Task.
Добавить поля, сеттеры, геттеры, конструктор без аргументов и конструктор со всеми аргументами.

**Comment by ArchyGit** [comment]
Реализовал базовую версию, запушил в новый бранч. Нужна проверка/критика.

**Comment by VasilyMartynov** [comment]
Class is done. Whenever we need it - we can return to it.
